### ISSUE TITLE
IMA plugin load the adTagUrl immediately

### ISSUE THREAD

**Issue by tomybyte** [kaltura/playkit-js-ima#106]
##### Prerequisites
- [X] Have you checked for duplicate [issues](https://github.com/kaltura/playkit-js-ima/issues): yes
- [X] Which Plugin [version](https://github.com/kaltura/playkit-js-ima/releases) are you using:  0.10.8 
- [X] Can you reproduce the issue with our latest release version: not tested
- [x] Can you reproduce the issue with the latest code from master: yes
- [X] What browser and OS names and versions are you using: Chrome,Firefox
- [X] If applicable, add test code or test page to reproduce: 
```
https://account.hyvyd.com/Player_test_kaltura_dfp_k&t.html
```

##### Expected behavior
What you expected to happen

The Player is configured autoplay: false therefore the IMA plugin should load the adTagUrl, the VAST Tags and the Ad Counter Pixel on press Play Button

##### Actual behavior
What actually happened

the IMA plugin load the adTagUrl, the VAST Tags and the Ad Counter Pixel immediately (on Player Initialisation)
this caused wrong Ad Counter Pixel also if the Player never start

##### Console output
```
not relevant
```

**Comment by tomybyte** [comment]
So may be there is an undocumented configuration parameter to prevent this behavior?

**Comment by OrenMe** [comment]
hi @tomybyte,
The player optimizes the ad tag loading so ad manager will already be available when play is requested.
The ad creative itself should only be loaded once ad starts and so are the tracking impressions.
Can you please add more details regarding what is loaded before the playback that is causing ad trackers to count it?

**Comment by tomybyte** [comment]
Hi @OrenMe,

these are the called VAST Tags contained in the adTagUrl waterfall (DFP Master-Video-Tag) 
![grafik](https://user-images.githubusercontent.com/2370936/57214035-e49b7580-6fe8-11e9-879b-e50154aecac6.png)

and these are the Counter Pixel fired to pubads.g.doubleclick.net and pagead2.googlesyndication.com
![grafik](https://user-images.githubusercontent.com/2370936/57213900-7b1b6700-6fe8-11e9-998a-28b234064b7d.png)

I hope that is the correct answer to your question...

Sincerely

**Comment by tomybyte** [comment]
Hi @OrenMe,
Is there any news
Sincerely

**Comment by OrenMe** [comment]
Hi @tomybyte sorry for the delay.
Thanks for the explanation BTW, and I'm aware of how VAST/VMAP works.
I was wondering which exact tracking events are being fired? is this the DFP specific extension tracking pixels or standard vast TrackingEvents?

The player supports standard VAST tracking events which are emitted in case creative is loaded.

**Comment by tomybyte** [comment]
Hi @OrenMe,
so I'm not sure what Google counts there, but I find it worrying that Google counts at all, because there is a possibility that the video is never watched.
The other thing is, how can you be sure that calling the VAST tag might not trigger the capping for an ad?
Sincerely

**Comment by OrenMe** [comment]
@tomybyte in general we follow IMA recommendations for reducing overall latency with ad playback.
See here: https://developers.google.com/interactive-media-ads/docs/sdks/html5/latency

There are additional things to take into considerations like the overall join time and other metrics that show how user experience contribute to user actually watching the ad and continuing to viewing the content.

I will need to take it with the team, but in general I can offer as a workaround that you place a video poster and a play button and when user clicks it then call setup.
This will cause ad to load only when user clicks play, but pay attention this will probably have some implications with browser audible autoplay restrictions.

**Comment by tomybyte** [comment]
Hi @OrenMe,
thank you for your explanation and recommendation!
In this case the issue seems to have been resolved.

**Comment by OrenMe** [comment]
great @tomybyte, thanks for confirming.
