### ISSUE TITLE
Stopped source will autoplay if AD_ERROR occures on preroll URL

### ISSUE THREAD

**Issue by romanzipp** [kaltura/playkit-js-ima#140]
##### Prerequisites
- [x] Have you checked for duplicate [issues](https://github.com/kaltura/playkit-js-ima/issues)
- [x] Which Plugin [version](https://github.com/kaltura/playkit-js-ima/releases) are you using: 0.18.2
- [x] Can you reproduce the issue with our latest release version: yes
- [x] Can you reproduce the issue with the latest code from master: yes
- [x] What browser and OS names and versions are you using: Ubuntu 18.04 / Google Chrome 77.0.3865.90
- [x] If applicable, add test code or test page to reproduce: 

**IMA plugin config**

```js
{
    adTagUrl: null,
    debug: true,
    delayInitUntilSourceSelected: true,
    disableMediaPreload: false,
    vpaidMode: 'ENABLED',
    adsRenderingSettings: {
        restoreCustomPlaybackStateOnAdBreakComplete: true,
        enablePreloading: true,
        useStyledLinearAds: false,
        useStyledNonLinearAds: false,
        bitrate: -1,
        autoAlign: true,
        loadVideoTimeout: 10000
    }
}
```

**Kaltura advertising config**

```js
{
    advertising: {
        adBreaks: [
            {
                position: 0,
                played: false,
                ads: [
                    {
                        url: '...'
                    }
                ]
            }
        ]
    }
}
```

##### Expected behavior
If the preroll ad request fails, the player should not start. The error occures with `restoreCustomPlaybackStateOnAdBreakComplete` set to `true` and `false`.

##### Actual behavior
The playback starts although the player is initially stopped. The actual `AD_ERROR` was caused due to ad-blocking (`net::ERR_BLOCKED_BY_CLIENT`)

##### Console output
![2019-10-10_18:39:12](https://user-images.githubusercontent.com/11266773/66588834-95580300-eb8d-11e9-9569-c3084349574b.png)

##### JSFiddle

https://jsfiddle.net/romanzipp/zyhbdurt/16/

**Comment by OrenMe** [comment]
Thanks @romanzipp, can you please share a test link that reproduces this.
@yairans PTAL

**Comment by romanzipp** [comment]
I've created **[this fiddle](https://jsfiddle.net/romanzipp/zyhbdurt/14/)**.
The autoplay error can be reproduced both by setting an invalid ad tag url (`adUrl = 'http://localhost/missing'`) or enabling an adblock rule which also triggers the network error.

**Comment by OrenMe** [comment]
thanks for the sample! we will look into it.
Just an FYI - the `advertising` feature is still in experimental mode and should be stable by end of this Q.
Very glad you were able to set it up already and get a working use case... and find a bug :wink:
How did you manage to set the sample? do you have a Kaltura account or you did it from the github repos?

**Comment by romanzipp** [comment]
Alright, didn't know the IMA version still in an experimental state since the new ad layout has been patched into the latest kaltura-player version.

> How did you manage to set the sample?

I've just pulled in the latest dependencies from npms & Github
